# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pcie-advss"
BBFILE_PATTERN_meta-pcie-advss = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pcie-advss = "6"

LAYERDEPENDS_meta-pcie-advss = "core"
LAYERSERIES_COMPAT_meta-pcie-advss = "scarthgap"
